shepherdjerred/homelab

- cdk8s/src/versions/versions.ts
This PR updates the scout-for-lol version to 1.0.9
> chore: update scout-for-lol version to 1.0.9

- cdk8s/src/versions/versions.ts
This PR updates the scout-for-lol version to 1.0.10
> chore: update scout-for-lol version to 1.0.10

- cdk8s/src/versions/versions.ts
This PR updates the scout-for-lol version to 1.0.11
> chore: update scout-for-lol version to 1.0.11

- cdk8s/src/versions/versions.ts
This PR updates the scout-for-lol version to 1.0.12
> chore: update scout-for-lol version to 1.0.12

- cdk8s/src/versions/versions.ts
This PR updates the scout-for-lol version to 1.0.13
> chore: update scout-for-lol version to 1.0.13

- cdk8s/src/versions/versions.ts
This PR updates the scout-for-lol version to 1.0.3
> chore: update scout-for-lol version to 1.0.3

- cdk8s/src/versions/versions.ts
This PR updates the scout-for-lol version to 1.0.4
> chore: update scout-for-lol version to 1.0.4

- cdk8s/src/versions/versions.ts
This PR updates the scout-for-lol version to 1.0.1
> chore: update scout-for-lol version to 1.0.1

- cdk8s/src/versions/versions.ts
This PR updates the scout-for-lol version to 1.0.6
> chore: update scout-for-lol version to 1.0.6

- cdk8s/src/versions/versions.ts
This PR updates the scout-for-lol version to 1.0.2
> chore: update scout-for-lol version to 1.0.2

- cdk8s/src/versions/versions.ts
This PR updates the scout-for-lol version to 1.0.7
> chore: update scout-for-lol version to 1.0.7

- cdk8s/src/versions/versions.ts
This PR updates the scout-for-lol version to 1.0.14
> chore: update scout-for-lol version to 1.0.14

- cdk8s/src/versions/versions.ts
This PR updates the scout-for-lol version to 1.0.16
> chore: update scout-for-lol version to 1.0.16

- cdk8s/src/versions/versions.ts
This PR updates the scout-for-lol version to 1.0.17
> chore: update scout-for-lol version to 1.0.17

- cdk8s/src/versions/versions.ts
This PR updates the scout-for-lol version to 1.0.19
> chore: update scout-for-lol version to 1.0.19

- cdk8s/src/versions/versions.ts
This PR updates the scout-for-lol version to 1.0.21
> chore: update scout-for-lol version to 1.0.21

- cdk8s/src/versions/versions.ts
This PR updates the scout-for-lol version to 1.0.23
> chore: update scout-for-lol version to 1.0.23

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.25
> chore: update scout-for-lol version to 1.0.25

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.26
> chore: update scout-for-lol version to 1.0.26

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.28
> chore: update scout-for-lol version to 1.0.28

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.29
> chore: update scout-for-lol version to 1.0.29

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.33
> chore: update scout-for-lol version to 1.0.33

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.34
> chore: update scout-for-lol version to 1.0.34

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.36
> chore: update scout-for-lol version to 1.0.36

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.37
> chore: update scout-for-lol version to 1.0.37

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.38
> chore: update scout-for-lol version to 1.0.38

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.43
> chore: update scout-for-lol version to 1.0.43

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.44
> chore: update scout-for-lol version to 1.0.44

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.45
> chore: update scout-for-lol version to 1.0.45

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.46
> chore: update scout-for-lol version to 1.0.46

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.47
> chore: update scout-for-lol version to 1.0.47

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.48
> chore: update scout-for-lol version to 1.0.48

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.49
> chore: update scout-for-lol version to 1.0.49

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.50
> chore: update scout-for-lol version to 1.0.50

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.51
> chore: update scout-for-lol version to 1.0.51

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.52
> chore: update scout-for-lol version to 1.0.52

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.58
> chore: update scout-for-lol version to 1.0.58

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.59
> chore: update scout-for-lol version to 1.0.59

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.60
> chore: update scout-for-lol version to 1.0.60

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.61
> chore: update scout-for-lol version to 1.0.61

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.62
> chore: update scout-for-lol version to 1.0.62

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.63
> chore: update scout-for-lol version to 1.0.63

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.64
> chore: update scout-for-lol version to 1.0.64

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.67
> chore: update scout-for-lol version to 1.0.67

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.68
> chore: update scout-for-lol version to 1.0.68

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.69
> chore: update scout-for-lol version to 1.0.69

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.70
> chore: update scout-for-lol version to 1.0.70

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.72
> chore: update scout-for-lol version to 1.0.72

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.73
> chore: update scout-for-lol version to 1.0.73

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.74
> chore: update scout-for-lol version to 1.0.74

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.75
> chore: update scout-for-lol version to 1.0.75

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.76
> chore: update scout-for-lol version to 1.0.76

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.77
> chore: update scout-for-lol version to 1.0.77

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.78
> chore: update scout-for-lol version to 1.0.78

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.79
> chore: update scout-for-lol version to 1.0.79

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.80
> chore: update scout-for-lol version to 1.0.80

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.81
> chore: update scout-for-lol version to 1.0.81

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.83
> chore: update scout-for-lol version to 1.0.83

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.84
> chore: update scout-for-lol version to 1.0.84

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.85
> chore: update scout-for-lol version to 1.0.85

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.86
> chore: update scout-for-lol version to 1.0.86

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.88
> chore: update scout-for-lol version to 1.0.88

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.89
> chore: update scout-for-lol version to 1.0.89

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.100
> chore: update scout-for-lol version to 1.0.100

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.101
> chore: update scout-for-lol version to 1.0.101

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.103
> chore: update scout-for-lol version to 1.0.103

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.108
> chore: update scout-for-lol version to 1.0.108

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.109
> chore: update scout-for-lol version to 1.0.109

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.110
> chore: update scout-for-lol version to 1.0.110

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.111
> chore: update scout-for-lol version to 1.0.111

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.112
> chore: update scout-for-lol version to 1.0.112

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.116
> chore: update scout-for-lol version to 1.0.116

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.117
> chore: update scout-for-lol version to 1.0.117

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.118
> chore: update scout-for-lol version to 1.0.118

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.119
> chore: update scout-for-lol version to 1.0.119

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.120
> chore: update scout-for-lol version to 1.0.120

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.121
> chore: update scout-for-lol version to 1.0.121

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.132
> chore: update scout-for-lol version to 1.0.132

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.135
> chore: update scout-for-lol version to 1.0.135

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.139
> chore: update scout-for-lol version to 1.0.139

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.141
> chore: update scout-for-lol version to 1.0.141

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.142
> chore: update scout-for-lol version to 1.0.142

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.144
> chore: update scout-for-lol version to 1.0.144

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.147
> chore: update scout-for-lol version to 1.0.147

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.158
> chore: update scout-for-lol version to 1.0.158

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.160
> chore: update scout-for-lol version to 1.0.160

- cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.165
> chore: update scout-for-lol version to 1.0.165

- .dagger/src/index.ts
- src/cdk8s/src/services/home/ha.ts
- src/cdk8s/src/versions.ts
HA image versioning now uses GitHub Actions run numbers for a 1:1 mapping between CI builds and deployed versions.
*   `src/cdk8s/src/versions.ts` was updated to include a new entry for the custom HA image, `"shepherdjerred/homelab": "latest"`. This entry serves as a placeholder to be dynamically updated during CI.
*   In `src/cdk8s/src/services/home/ha.ts`, the hardcoded `latest` tag for the custom HA image was replaced with a reference to `versions["shepherdjerred/homelab"]`, ensuring the deployment consumes the version from the `versions.ts` file.
*   A new Dagger function, `updateHaVersion()`, was added to `.dagger/src/index.ts`. This function uses `sed` to programmatically update the `"shepherdjerred/homelab"` entry in `versions.ts` with the GitHub Actions run number.
*   The Dagger …
> Build and publish HA image with run number

- src/cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.40
> chore: update scout-for-lol version to 1.0.40

- src/cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.92
> chore: update scout-for-lol version to 1.0.92

- src/cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.96
> chore: update scout-for-lol version to 1.0.96

- src/cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.98
> chore: update scout-for-lol version to 1.0.98

- src/cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.99
> chore: update scout-for-lol version to 1.0.99

- src/cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.102
> chore: update scout-for-lol version to 1.0.102

- src/cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.123
> chore: update scout-for-lol version to 1.0.123

- src/cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.124
> chore: update scout-for-lol version to 1.0.124

- src/cdk8s/src/versions.ts
This PR updates the scout-for-lol version to 1.0.127
> chore: update scout-for-lol version to 1.0.127
